dist: trusty
language: python
sudo: false

install:
  - make deps
script:
  - make test
after_success:
  - make codedev

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy2
    - python: pypy3
      env: TOXENV=pypy3
