from setuptools import setup

setup(name='ostruct',
      version='2.1.2',
      description='OpenStruct Data Structure',
      long_description='OpenStruct, the felixble data structure.',
      classifiers=[
          'Programming Language :: Python',
          'Programming Language :: Python :: 2',
          'Programming Language :: Python :: 2.6',
          'Programming Language :: Python :: 2.7',
          'Programming Language :: Python :: 3',
          'Programming Language :: Python :: 3.3',
          'Programming Language :: Python :: 3.4',
          'Intended Audience :: Developers',
          'License :: OSI Approved :: MIT License',
          'Operating System :: OS Independent',
          'Topic :: Software Development',
          'Topic :: Software Development :: Libraries',
          'Topic :: Software Development :: Libraries :: Python Modules',
          'Development Status :: 5 - Production/Stable',
      ],
      keywords=[
          'ostruct',
          'openstruct',
          'data structure',
          'data structures',
      ],
      author='Hamid Nazari',
      author_email='hn@linux.com',
      url='http://github.com/hamidnazari/python-ostruct',
      license='MIT',
      packages=['ostruct'],
      zip_safe=False)
