[tox]
env_list = py{310,311,312,313,314}
isolated_build = true

[testenv]
extras = test
commands = pytest -v --cov=ostruct --cov-report=term-missing --cov-report=xml:{toxworkdir}/coverage-{envname}.xml --junitxml={toxworkdir}/junit-{envname}.xml
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14
