name: Build and Publish

on:
  release:
    types:
      - published

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build distribution packages
        run: make package

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-ostruct-distributions
          path: dist/

  publish:
    needs: package
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/python-ostruct

    permissions:
      id-token: write

    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-ostruct-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
